// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbwRLYiAsbQS5KUE50G9PM-SNash1WM1U',
    appId: '1:946174817141:android:003be7859a68f42ead593c',
    messagingSenderId: '946174817141',
    projectId: 'app-robot-252f7',
    databaseURL: 'https://app-robot-252f7-default-rtdb.firebaseio.com',
    storageBucket: 'app-robot-252f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC50qhJwPUULoV19d086KBTxDJZoMwoiLI',
    appId: '1:946174817141:ios:a98e845714e0e4a1ad593c',
    messagingSenderId: '946174817141',
    projectId: 'app-robot-252f7',
    databaseURL: 'https://app-robot-252f7-default-rtdb.firebaseio.com',
    storageBucket: 'app-robot-252f7.firebasestorage.app',
    iosBundleId: 'com.example.tasteAndroid',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCse0vE76yP8eVLzSejaz1XGbdNsuz_zJk',
    appId: '1:946174817141:web:d9fb1441b953bddead593c',
    messagingSenderId: '946174817141',
    projectId: 'app-robot-252f7',
    authDomain: 'app-robot-252f7.firebaseapp.com',
    databaseURL: 'https://app-robot-252f7-default-rtdb.firebaseio.com',
    storageBucket: 'app-robot-252f7.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC50qhJwPUULoV19d086KBTxDJZoMwoiLI',
    appId: '1:946174817141:ios:a98e845714e0e4a1ad593c',
    messagingSenderId: '946174817141',
    projectId: 'app-robot-252f7',
    databaseURL: 'https://app-robot-252f7-default-rtdb.firebaseio.com',
    storageBucket: 'app-robot-252f7.firebasestorage.app',
    iosBundleId: 'com.example.tasteAndroid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCse0vE76yP8eVLzSejaz1XGbdNsuz_zJk',
    appId: '1:946174817141:web:039aa5593db5b397ad593c',
    messagingSenderId: '946174817141',
    projectId: 'app-robot-252f7',
    authDomain: 'app-robot-252f7.firebaseapp.com',
    databaseURL: 'https://app-robot-252f7-default-rtdb.firebaseio.com',
    storageBucket: 'app-robot-252f7.firebasestorage.app',
  );

}